---
title: "Lista 1 exercício 6"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    social: menu
    source_code: embed
runtime: shiny
---

```{r global, include=FALSE}
setwd("C:/Users/joao.caldas/Desktop/Análise Exploratoria")
library(tidyverse)
library(flexdashboard)
library(ggplot2)
library(gridExtra)
library(readxl)
library(dplyr)
dados <- read_excel( "C:/Users/joao.caldas/Desktop/Análise Exploratoria/Lista_de_exercicios_1.xlsx")

dados1 = dados[,  c("Week (2008-2009)", "Period", "Avg. Time on Site (secs.)", "Profit")]
head(dados1)

dados2 = dados1 %>%
  rename("Semana" = "Week (2008-2009)")%>%
  rename("Periodo" = "Period")%>%
  rename("Tempo_no_site" = "Avg. Time on Site (secs.)")%>%
  rename("Lucro" = "Profit")

dados2$Periodo = factor(dados2$Periodo, levels = c("Shakedown", "Analysis 1", "Promotion", "Analysis 2"))
```
```{r}

```

Column {data-width=650}
-----------------------------------------------------------------------

### Dispersão  Tempo no site x log Lucro


```{r}
ggplot(dados2, aes(x = Tempo_no_site,
                   y = log(Lucro),
                   color = Periodo)) +
  geom_point(alpha = 5.5, size = 2.5) +
  labs(title = "Tempo no site x Lucro",
       subtitle = "Dispersao",
       x="Tempo no site",
       y="Log Lucro",
       color = "") +
  theme_minimal()

```

### Boxplot Perído x log Lucro

```{r}
ggplot(dados2, aes(x = Periodo,
                   y = log(Lucro),
                   fill = Periodo)) +
  geom_boxplot() +
  scale_fill_brewer("Blues") +
  labs(title = "Periodo x Lucro",
       subtitle = "boxplot",
       x="Período",
       y="log lucro")  +
  guides(fill = "none") +
  theme_minimal()
```



Column {data-width=350}
-----------------------------------------------------------------------

### Detalhes
```{r}
renderTable({
  selectedData()
})
```



